In [6]:
from datetime import datetime
now = datetime.now()
print(now.year)

2023


In [8]:
#Numpy - Numerical Python

mylist = [4,5,8,2,2]

In [9]:
import numpy as np

In [14]:
arr = np.array(mylist)
arr
#print(arr)

array([4, 5, 8, 2, 2])

In [15]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
import numpy as np
import pandas as pd

In [5]:
from numpy.random import randn

In [7]:
np.random.seed(101)

In [9]:
data = pd.DataFrame(randn(3,4),['A','B','C'],['W','X','Y','Z'])

In [10]:
data

W         X         Y         Z
A  0.188695 -0.758872 -0.933237  0.955057
B  0.190794  1.978757  2.605967  0.683509
C  0.302665  1.693723 -1.706086 -1.159119

In [11]:
data.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [14]:
data['W']

A    0.188695
B    0.190794
C    0.302665
Name: W, dtype: float64

In [15]:
data['New'] = data['X']+data['Y']

In [16]:
data

W         X         Y         Z       New
A  0.188695 -0.758872 -0.933237  0.955057 -1.692109
B  0.190794  1.978757  2.605967  0.683509  4.584725
C  0.302665  1.693723 -1.706086 -1.159119 -0.012363

In [19]:
pd.unique(data['Z'])

array([ 0.95505651,  0.68350889, -1.15911942])