In [1]:
import numpy as np

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
list1 = [1,4,6,7,8,9]
c=np.array(list1)
print(c*2)
print(list1)

[ 2  8 12 14 16 18]
[1, 4, 6, 7, 8, 9]


In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
for x in list1:
    print(x)

1
4
6
7
8
9


In [9]:
list3 = []
for x in list1:
    list3.append(x*2)
    
print(list3)

[2, 8, 12, 14, 16, 18]
